### ISSUE TITLE
Nextcloud Update - Lost App

### ISSUE THREAD

**Issue by Moimemeici** [hoellen/dockerfiles#27]
Hello and sorry for my english.
But, i have an problem.
When i update the docker, i need reinstall all app.
It's normal ?
Best regards

**Comment by hoellen** [comment]
No this is not normal. Can you please give some more information (e.g. docker-compose files, Nextcloud config, logs, etc.) about your installation. I believe you are missing the second app directory in your config.

**Comment by Moimemeici** [comment]
i have 2 instances 
one with : 

```
    volumes:
      - /cloud/data:/data
      - /cloud/config/config_xxx:/config
      - /cloud/apps:/apps2
      - /cloud/themes_xxx:/nextcloud/themes
```

and other 
```

    volumes:
      - /cloud/data_test:/data
      - /cloud/config/config_test:/config
      - /cloud/apps_test:/apps2
      - /cloud/themes_test:/nextcloud/themes
```

First not good but second is good

**Comment by Moimemeici** [comment]
i have 2 instances 
one with : 

```
  nextcloud-XXX:
    image: hoellen/nextcloud:latest
    container_name: nextcloud-XXX
    restart: always
    environment:
      - UID=991
      - GID=991
      - UPLOAD_MAX_SIZE=10G
      - APC_SHM_SIZE=128M
      - OPCACHE_MEM_SIZE=128
      - REDIS_MAX_MEMORY=64mb
      - CRON_PERIOD=15m
      - TZ=Europe/Paris
      - DB_TYPE=mysql
      - DB_NAME=XXXXXXXXXXXX
      - DB_USER=XXXXXXXXXXXX
      - DB_PASSWORD=XXXXXXXXXXXXXXXXXX
      - DB_HOST=mariadb-XXX
    volumes:
      - /cloud/data:/data
      - /cloud/config/config_XXX:/config
      - /cloud/apps:/apps2
      - /cloud/themes_XXX:/nextcloud/themes
    depends_on:
      - mariadb-XXX
      - solr
      - redis
```

and other 

```
  nextcloud-test:
    image: hoellen/nextcloud:latest
    container_name: nextcloud-test
    restart: always
    environment:
      - UID=991
      - GID=991
      - UPLOAD_MAX_SIZE=10G
      - APC_SHM_SIZE=128M
      - OPCACHE_MEM_SIZE=128
      - REDIS_MAX_MEMORY=64mb
      - CRON_PERIOD=15m
      - TZ=Europe/Paris
      - DB_TYPE=mysql
      - DB_NAME=XXXXXXXXXXXX
      - DB_USER=XXXXXXXXXXXX
      - DB_PASSWORD=XXXXXXXXXXXX
      - DB_HOST=mariadb-test
    volumes:
      - /cloud/data_test:/data
      - /cloud/config/config_test:/config
      - /cloud/apps_test:/apps2
      - /cloud/themes_test:/nextcloud/themes
    depends_on:
      - mariadb-test
      - solr
      - redis
```

First not good but second is good
