### ISSUE TITLE
Nextcloud Push

### ISSUE THREAD

**Issue by hoellen** [hoellen/dockerfiles#46]
There is a new "high performance backend" for Nextcloud. It uses _push_ to communicate with the Nextcloud clients. As we already use Nginx as a reverse proxy, it could be integrated/controlled very easily via docker env variables. 

Should it be optional/default?

Useful links:
- https://nextcloud.com/blog/nextcloud-hub-21-out-with-up-to-10x-better-performance-whiteboard-and-more-collaboration-features/
- https://nextcloud.com/blog/nextcloud-faster-than-ever-introducing-files-high-performance-back-end/
- https://github.com/nextcloud/notify_push

_Users of the Docker image can leave a reaction or comment here, if they have specific suggestions/concerns._

**Comment by waja** [comment]
Hi @hoellen,

thanks for maintaining this great project.

I think it would be nice to have the HPB shipped by default but (maybe for now) not enabled by default but as you suggested controlled via env variables.

Many thanks, Jan.

**Comment by GUNT0815** [comment]
Hi @Hoellen,

I would vote for:

- best performance/ HPB should be enabled by default
- should be "switched off" via environment variables

I think this is the most convenient approach for the SOHO users out there, but also allows different configuration in case.

Thanks, Udo

**Comment by hathagat** [comment]
I vote for only adding the push location to the nginx config because there is an official HPB image already.
https://github.com/nextcloud/notify_push/blob/main/Dockerfile
https://hub.docker.com/r/icewind1991/notify_push

So we could use it the same way we use the database or redis:
```yaml
 notify_push:
   image: icewind1991/notify_push
   environment:
     - NEXTCLOUD_URL=https://myclouddomain.com/
     - DATABASE_URL=mysql://MYDBUSER:MYDBPASSWORD@db/nextcloud
     - DATABASE_PREIX=oc_
     - REDIS_URL=redis://:MYREDISPASSSWORD@redis
```

**Comment by waja** [comment]
> I vote for only adding the push location to the nginx config because there is an official HPB image already.

Adding another image creates lot of additional hassle. See https://github.com/nextcloud/docker/issues/1422 and https://github.com/nextcloud/notify_push/issues/11 for example.

You don't need to pass those variables, when you give `notify_push` the location of the nextcloud config.

You need also to deal with trusted proxies it seems.

**Comment by hathagat** [comment]
Yes, on the one hand you are right. It adds more complexity to the docker setup. On the other hand the complexity is not added to this image.
Additionally the HPB needs Redis, so you need an external image anyway. If HPB is enabled using an env variable only, it would not work out of the box.

From a conceptual point of view, this is just like Redis, OnlyOffice, Turn, Elasticsearch or similar: Another service for Nextcloud which can be added to the stack if required.

Anyways, I'm fine with both ways. :relaxed:
Atm HPB ist working for me in the seperate container.

**Comment by hoellen** [comment]
After thinking about it, I also don't want to include the push backend into the Nextcloud image. I see it like @hathagat, that it is something like Redis etc. that you can choose to use. We also support very small/limited user setups where you can run Nextcloud e.g. with sqlite. Also if you want to test things, there is less complexity preferred.

On the long run I want to provide an own image for the push backend with an easy-to-use config. But I still have to look into it.

**Comment by lexxxel** [comment]
@hoellen what is your conclusion today?

**Comment by waja** [comment]
> Atm HPB ist working for me in the seperate container.

@hathagat do you wonna share your docker compose config with us?

**Comment by hathagat** [comment]
> @hathagat do you wonna share your docker compose config with us?

Sure!

```yaml
 # https://github.com/instrumentisto/coturn-docker-image
 coturn:
   image: instrumentisto/coturn:latest
   container_name: nextcloud-turn
   networks:
     - frontends
   ports:
     - "3478:3478"
     - "3478:3478/udp"
     - '49160-49200/udp'
   volumes:
     - ${DOCKER_DATA_PATH}/nextcloud/turn/turnserver.conf:/etc/coturn/turnserver.conf
     - ${DOCKER_DATA_PATH}/nextcloud/turn/data:/var/lib/coturn
   command:
     - -n
     - --no-cli
     - --log-file=stdout
     - --min-port=49160
     - --max-port=49200
     - --realm=${NEXTCLOUD_DOMAIN}
     - --use-auth-secret
     - --static-auth-secret=${NEXTCLOUD_TURN_SECRET}
   environment:
     VIRTUAL_HOST: turn.${NEXTCLOUD_DOMAIN}
     VIRTUAL_PORT: 3478
   restart: always

 # https://github.com/strukturag/nextcloud-spreed-signaling
 signaling:
   container_name: nextcloud-signaling
   build: ./signaling
   image: my-signaling:latest
   depends_on:
     - coturn
     - nats
     - janus
   volumes:
     - ${DOCKER_DATA_PATH}/nextcloud/signaling/server.conf:/config/server.conf
   restart: always

 nats:
   container_name: nextcloud-nats
   image: nats:2.2.1
   command: ["-c", "/config/gnatsd.conf"]
   volumes:
     - ${DOCKER_DATA_PATH}/nextcloud/nats/gnatsd.conf:/config/gnatsd.conf
   restart: always

 janus:
   container_name: nextcloud-janus
   build: ./janus
   image: my-janus:latest
   command: ["janus", "--full-trickle"]
   restart: always
```

The `networks` and `environment` stuff is just for my Nginx setup. So you can ignore that parts. Using `network_mode: host` would make things easier for you in this regard.
The `signaling` service builds the Dockerfile from the official repository.

Basically I followed this [tutorial](https://markus-blog.de/index.php/2020/11/20/how-to-run-nextcloud-talk-high-performance-backend-with-stun-turnserver-on-ubuntu-with-docker-compose/).
